name: auth_actor
description: A new Flutter project.
publish_to: 'none' 
version: 1.2.0+3
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^2.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/fg.png"
  adaptive_icon_background: "#ffffff"